sudo: false
dist: trusty
language: php

cache:
  directories:
    - node_modules
    - $HOME/.composer/cache/files

php:
  - 7.0

services:
  - chrome: stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - php -S localhost:8000 index.php

install:
  - travis_retry npm install
  - npm list --depth=0

script:
  - npm run test