sudo: false
dist: trusty
language: php

cache:
  directories:
    - node_modules
    - $HOME/.composer/cache/files

php:
  - 7.0

addons:
  chrome: stable

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - php -S localhost:8000 index.php &
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8000 &

install:
  - travis_retry npm install
  - npm list --depth=0

script:
  - npm run test